### ISSUE TITLE
Migration from POD to SPM - GooglePlaces not work

### ISSUE THREAD

**Issue by salvatoreboemia** [googlemaps/ios-maps-sdk#30]
Hi 

I removed as POD

```
Removing GoogleMaps
Removing GooglePlaces
```

But in this SPM is not presented GooglePlaces?

Works fine only in the app delegate

`GMSServices.provideAPIKey("my key")`

But all the other ones not work
```
GMSAutocompleteFetcherDelegate
GMSPlacesClient.shared()
```

Cannot find 'GMSPlacesClient' in scope

etc...

I read also this docs:

- https://developers.google.com/maps/documentation/ios-sdk/config#swift-package-manager

any idea?

Thanks

**Comment by salvatoreboemia** [comment]
added all these as SPM

- https://github.com/googlemaps/ios-maps-sdk
- https://github.com/googlemaps/google-maps-ios
- https://github.com/googlemaps/ios-places-sdk

Now works

**Comment by wangela** [comment]
You should only need the first and third swift package; the middle one doesn't exist.

- https://github.com/googlemaps/ios-maps-sdk
- https://github.com/googlemaps/ios-places-sdk

Glad to hear it's working for you now.
