### ISSUE TITLE
Excessive Cache Growth in CCTClearcutLogger Directory Due to Continuous Camera Updates in Google Maps iOS SDK

### ISSUE THREAD

**Issue by fastdigoxin0l** [googlemaps/ios-maps-sdk#40]
#### Environment details

1. iOS 18
2. Using XCode 16.0
3. Google Maps iOS SDK 9.0.0 (also tried with 9.1.1)

#### Steps to reproduce

  1. Create a new iOS project and integrate the Google Maps iOS SDK.
  2. Implement a basic MapView.
  3. Set up the MapView to rotate by 1 degree every 10ms.
  4. Print the cache directory size (CCTClearcutLogger) to the console every second.

#### Code example
[Sample project](https://github.com/fastdigoxin0l/google-maps-log-test)

#### Description
We are experiencing an issue with the Google Maps iOS SDK where excessive logging causes the cache to grow uncontrollably during continuous camera updates. Our app continuously updates the camera position in MapView based on the device's GPS and compass readings. This setup has led to the creation of substantial log files in the cache directory CCTClearcutLogger, resulting in crashes for some users as the cache grows beyond 2GB.

This issue has been observed across multiple devices and iOS versions, notably on iPhone 12 mini running iOS 18, where the cache growth is approximately 2MB per minute during constant map updates. The rapid cache growth, likely due to each camera update being logged, eventually creates single large files that the SDK seems unable to handle.

#### Current Impact
This logging behavior results in excessive storage consumption and crashes for our users as the cache reaches unusable sizes.

**Comment by wangela** [comment]
As this is a bug about the Maps SDK for iOS, please file it on the [Maps SDK for iOS issue tracker](https://issuetracker.google.com/savedsearches/5050151). There have been reports about this crash from multiple libraries but none reported on the issue tracker, which is the officially supported queue where externally-reported issues are triaged for intake.
