### ISSUE TITLE
App crashes (memory) when setting map to GMSPolyline - if and only if the route is too long 

### ISSUE THREAD

**Issue by nayooti** [googlemaps/ios-maps-sdk#42]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
GMSPolyline+maps 
2. OS type and version
XCode 16.1
iOS 18.1 
GoogleMaps SDK 9.1.1
3. Library version and other environment information

#### Steps to reproduce

  Clone this demo project and launch the project.
  https://github.com/nayooti/GoogleMapsDemo
  
 In MapController.swift set GoogleMaps API Key.

`let apiKey = "YOUR_API_KEY"
`

 Start the app  preferably on a real device (the app caused my machine to crash).
 
 You will see 
` The app “App” has been killed by the operating system because it is using too much memory.
` 
 Now: in MapController in viewDidAppear draw a shorter polyline (20km)
 ```swift
    public override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        // crashes app
        // mapView.drawLine(from: berlin, to: munich, navigationType: .car)

        // does not crash app
        mapView.drawLine(from: berlin, to: potsdam)
    }
 ```
 
 The app won't crash.
 
 The code used to work in previous GoogleMaps versions. 
  
#### Code example

```
# example
```

#### Stack trace
```swift
# example
    fetchPolylineWithOrigin(
            start: CLLocation(latitude: from.coordinates.latitude, longitude: from.coordinates.longitude),
            dest: CLLocation(latitude: to.coordinates.latitude, longitude: to.coordinates.longitude),
            navigationType: navigationType
        ) { [weak self] polyline in

            guard let self = self else { return }

            let styles = [
                GMSStrokeStyle.solidColor(.systemBlue),
                GMSStrokeStyle.solidColor(.clear)
            ]

            polyline.strokeWidth = 6
            let lengths = [3, 2]

            polyline.spans = GMSStyleSpans(polyline.path!, styles, lengths as [NSNumber], GMSLengthKind.rhumb)
            // here the crash is happening
            polyline.map = self
        }
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by wangela** [comment]
As this is a bug about the Maps SDK for iOS, please file it on the [Maps SDK for iOS issue tracker](https://issuetracker.google.com/savedsearches/5050151).
